# Are religious Americans more likely to repay loans?
The recent rise of peer-to-peer lending has been stunning. Starting from zero a few years ago, platforms like Lending Club are already placing $10 billion of unsecured personal loans per year. 

The concept is simple: a borrower fills in an application, investors choose to fund part or all of the loan, and the platform takes care of fine details, like collecting payments and annoying late borrowers. In theory, this disintermediation of banks from consumer credit lowers borrowing rates, improves investor returns, and leaves a healthy margin for the platform's profits.

The platforms publish anonymized default history from previous loans. This data helps investors make smarter decisions about future loans - attracting more investment dollars. Investors use the data to try to pick loans with a high interest rate, but a lower likelihood of default.

## Data set
For now, I will use only 36 month loans originating before 2013 (maturing before 2016). For now, I will restrict my data set to 2012 (as we go back further, the underwriting standards change). If I fill rows to handle current loans (see below), I will bring in more recent data.

## Predictive factors
Many factors look to be of interest. Obvious ones include:
- FICO Score
- Debt to Income ratio
- Size of loan

Additional factors that people have provided some evidence for:
- Loan description length
  - Long descriptions are bad: http://drjasondavis.com/blog/2012/04/08/lending-club-loan-analysis-making-money-with-logistic-regression
  - Long descriptions are good: https://lendingclubmodeling.wordpress.com/2011/04/25/why-loan-descriptions-and-qa-matter/
- Loan purpose: http://blog.lendingrobot.com/research/predicting-the-number-of-payments-in-peer-lending/

Other useful articles:
- http://blog.lendingrobot.com/research/predicting-returns-for-ongoing-loans/
- http://kldavenport.com/gradient-boosting-analysis-of-lendingclubs-data/

## Analysis

### Predicted variable
We're ultimately concerned with risk-adjusted return. However, analysis is simpler with certain assumptions. These may be revisited in a future analysis:
- Risk-adjustment can be handled separately
- Return = interest rate - probability of default * loss given default
- PD follows the same hazard curve, regardless of risk grade or other factors
- LGD is the same for different risk grades and only depends on lateness severity

Therefore, we can focus on PD only.

Explore:
- shape of default curve at different risk grades
- chance of late payments developing into default at different grades
- recovery amounts at different grades
- do late fees help out?

## Conclusion

### Caveats
This study has focused on a methodology for answering sociological questions and predicting defaults. Other issues to resolve for successful investing in P2P include:
- API access: smart investors, such as hedge funds are rumored to quickly cream off the best loans. Any superior statistical view must also compete on execution speed.
- Returns should be risk-adjusted for proper comparison to alternative investments, such as the S&P 500. An examination of similar grades of unsecuritized personal loans (credit cards) across the entire credit cycle would help capture both beta and true risk of default.
- Lending Club uses NAR (Net Annualized Return, a non-standard method that assumes all current loans will pay 100%) http://danielodio.com/one-year-in-lending-money-to-complete-strangers-via-an-api-and-why-you-should-try-it
- Investment size: what is the proper amount to invest in each loan to achieve the Kelly Criterion?
- Loans do not receive capital gains treatment and are taxed as ordinary income.

## Load data from Lending Club
Lending Club provides information on all past applications (and current loan status)

## Input files
- **LoanStats3a.csv.zip:** 2007-2011 Lending Club default history from https://www.lendingclub.com/info/download-data.action
- **LoanStats3b.csv.zip:** 2012-2013 Lending Club default history
- **LoanStats3c.csv.zip:** 2013-2014 Lending Club default history (currently reading this one only)
- **LoanStats3d.csv.zip:** 2015-2015 Lending Club default history
  - According to http://www.lendingmemo.com/lendingrobot-investing-review/, lending standards changed drastically starting in 2013
- **ZIP_COUNTY_122015.xlsx:** list of zip codes and county codes
- **national_county.txt:** list of states and counties mapped to code from US Census
- **2010.csv:** list of US counties, population, congregations, and adherents from http://www.rcms2010.org/ 
  - This website also has info breaking down into specific religion
- **US_elect_county:** 2012 presidential elections by county from http://www.theguardian.com/news/datablog/2012/nov/07/us-2012-election-county-results-download

In [78]:
import pandas as pd
pd.set_option('display.max_columns', 100)
%matplotlib inline
# religious adherents 
zip_counties = pd.read_excel('ZIP_COUNTY_122015.xlsx', skiprows = 0, header = 0)
zip_counties['ZIP'] = zip_counties['ZIP'].str.zfill(5)
zip_counties.head()

AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas

In [76]:
import pandas as pd
pd.set_option('display.max_columns', 100)
%matplotlib inline
# religious adherents 
national_county = pd.read_csv('national_county.txt', 
    names=['State', 'State_Code', 'County_Code', 'County', 'H1'], dtype={1: str, 2: str})
# combine into needed fields
national_county['County_Code_Full'] = national_county['State_Code'] + national_county['County_Code']
national_county['County_Full'] = national_county['County'].str[:-7] + ', ' + national_county['State']
national_county.head()

,State,State_Code,County_Code,County,H1,County_Code_Full,County_Full
0,AL,01,001,Autauga County,H1,01001,"Autauga, AL"
1,AL,01,003,Baldwin County,H1,01003,"Baldwin, AL"
2,AL,01,005,Barbour County,H1,01005,"Barbour, AL"
3,AL,01,007,Bibb County,H1,01007,"Bibb, AL"
4,AL,01,009,Blount County,H1,01009,"Blount, AL"

In [58]:
import pandas as pd
pd.set_option('display.max_columns', 100)
%matplotlib inline
# religious adherents 
religion = pd.read_csv('2010.csv', skiprows = 2, header = 1)
religion.head()

,County or Equivalent,Population,PopRank,Adherents,AdhRank,Congregations,ConRank,Adherents %,Adh% Rank,Congregations Per 10K People,Con Per 10K Rank
0,"Autauga, AL",54571,917,36938,691,106,831,67.7,546,19,1799
1,"Baldwin, AL",182265,338,96918,303,271,248,53.2,1329,15,2268
2,"Barbour, AL",27457,1516,15101,1392,89,1024,55.0,1206,32,701
3,"Bibb, AL",22915,1693,11430,1671,81,1152,49.9,1564,35,539
4,"Blount, AL",57322,884,37352,685,156,510,65.2,662,27,1072

In [35]:
import pandas as pd
pd.set_option('display.max_columns', 100)
%matplotlib inline
# 2012-2013 loan data - files are available from deeper history
# had to unzip file
past_loans = pd.read_csv('LoanStats3b.csv', header = 1, index_col=0, skiprows=0, skip_footer=2, engine='python')
past_loans['term'] = past_loans['term'].astype('category')
past_loans['grade'] = past_loans['grade'].astype('category')
past_loans['sub_grade'] = past_loans['sub_grade'].astype('category')
past_loans['home_ownership'] = past_loans['home_ownership'].astype('category')
past_loans['verification_status'] = past_loans['verification_status'].astype('category')

# Making assumption that any currently late loans are bad; may need to revisit
# Assumptions from Lending Club https://www.lendingclub.com/account/investorReturnsAdjustments.action
# Current 0% loss
# In Grace Period 28% loss
# Late 16-30 days 58% loss
# Late 31-120 days 74% loss
# Default 89% loss
di = {'Current': 'Good', 'Fully Paid': 'Good', 'Charged Off': 'Bad', 'Late (31-120 days)': 'Bad',
       'In Grace Period': 'Bad', 'Late (16-30 days)': 'Bad', 'Default': 'Bad'}
# past_loans.replace({'loan_status': di}, inplace=True)
past_loans['loan_status'] = past_loans['loan_status'].astype('category')
past_loans['pymnt_plan'] = past_loans['pymnt_plan'].astype('category')
past_loans['purpose'] = past_loans['purpose'].astype('category')
past_loans['application_type'] = past_loans['application_type'].astype('category')

# convert dates
past_loans['issue_d'] = pd.to_datetime(past_loans['issue_d'])
past_loans['earliest_cr_line'] = pd.to_datetime(past_loans['earliest_cr_line'])
past_loans['last_pymnt_d'] = pd.to_datetime(past_loans['last_pymnt_d'])
past_loans['next_pymnt_d'] = pd.to_datetime(past_loans['next_pymnt_d'])
past_loans['last_credit_pull_d'] = pd.to_datetime(past_loans['last_credit_pull_d'])
past_loans['issue_d'] = pd.to_datetime(past_loans['issue_d'])

# convert floats
past_loans['int_rate'] = pd.to_numeric(past_loans['int_rate'].str.extract('(.*)%'))/100

# drop pointless data
past_loans=past_loans.dropna(axis=1,how='all')
past_loans.drop('application_type',axis = 1) # only contains "individual"

# drop data that's not 2012 origination and 36 months term
past_loans = past_loans.drop(past_loans[(past_loans.issue_d >= '2012-07-01') | (past_loans.term == ' 60 months')].index)

past_loans.head()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1377559,1622372,2500,2500,2500,36 months,0.1465,86.24,C,C2,value concepts inc,10+ years,MORTGAGE,53000,Source Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/20/12 > home repairs th...,home_improvement,loan for life,306xx,GA,17.00,0,1987-03-01,0,30,NaN,8,0,3222,54.6%,15,f,0,0,3104.435553,3104.44,2500,604.44,0,0,0,2015-07-01,89.38,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,2,NaN,1080,74.3,0,0,NaN,NaN,NaN,NaN,3,103,NaN,11,30,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,33.3,0,0,NaN,12315,4200,NaN
1377635,1621835,3000,3000,2750,36 months,0.0790,93.88,A,A4,Washoe County School District,10+ years,MORTGAGE,45600,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,car,My Car,894xx,NV,8.21,0,1998-05-01,0,NaN,NaN,4,0,1046,26.1%,21,f,0,0,3379.306095,3097.70,3000,379.31,0,0,0,2015-07-01,96.03,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,1046,0,NaN
1377314,1621503,5600,5600,5600,36 months,0.1922,205.90,D,D5,OpenText,6 years,RENT,76320,Source Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/20/12 > Consolidation<b...,debt_consolidation,Consloan,323xx,FL,17.30,0,2008-09-01,0,NaN,NaN,9,0,3445,91.5%,13,f,0,0,7093.693707,7093.69,5600,1493.69,0,0,0,2014-05-01,2783.95,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,5,NaN,210,90.0,0,0,NaN,NaN,NaN,NaN,0,12,NaN,12,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,29364,2100,NaN
1327173,1572525,2800,2800,2800,36 months,0.0762,87.26,A,A3,The Dawson Academy,7 years,MORTGAGE,65000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/20/12 > This loan is go...,major_purchase,Spa Loan,140xx,NY,5.32,0,1992-02-01,0,NaN,NaN,4,0,818,4.1%,6,f,0,0,3141.029828,3141.03,2800,341.03,0,0,0,2015-07-01,89.64,NaT,2015-06-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,1,NaN,17782,4.4,0,0,NaN,NaN,NaN,NaN,0,139,NaN,9,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,0.0,0,0,NaN,12529,18600,NaN
1363816,1607830,1925,1925,1925,36 months,0.1074,62.79,B,B2,PPT,< 1 year,OWN,20700,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/20/12 > Help pay for ki...,home_improvement,Materials for home addition.,857xx,AZ,4.23,0,2002-09-01,2,NaN,NaN,7,0,2387,21.3%,10,f,0,0,1975.565136,1975.57,1925,50.57,0,0,0,2012-10-01,1850.67,NaT,2014-05-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,6,NaN,4702,22.9,0,0,NaN,NaN,NaN,NaN,0,11,NaN,0,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,50.0,0,0,NaN,12834,6100,NaN

In [54]:
past_loans.head(100)

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1377559,1622372,2500,2500,2500.000000,36 months,0.1465,86.24,C,C2,value concepts inc,10+ years,MORTGAGE,53000,Source Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/20/12 > home repairs th...,home_improvement,loan for life,306xx,GA,17.00,0,1987-03-01,0,30,NaN,8,0,3222,54.6%,15,f,0,0,3104.435553,3104.44,2500.00,604.44,0.00,0.00,0.000,2015-07-01,89.38,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,2,NaN,1080,74.3,0,0,NaN,NaN,NaN,NaN,3,103,NaN,11,30,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,33.3,0,0,NaN,12315,4200,NaN
1377635,1621835,3000,3000,2750.000000,36 months,0.0790,93.88,A,A4,Washoe County School District,10+ years,MORTGAGE,45600,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,car,My Car,894xx,NV,8.21,0,1998-05-01,0,NaN,NaN,4,0,1046,26.1%,21,f,0,0,3379.306095,3097.70,3000.00,379.31,0.00,0.00,0.000,2015-07-01,96.03,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,1046,0,NaN
1377314,1621503,5600,5600,5600.000000,36 months,0.1922,205.90,D,D5,OpenText,6 years,RENT,76320,Source Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/20/12 > Consolidation<b...,debt_consolidation,Consloan,323xx,FL,17.30,0,2008-09-01,0,NaN,NaN,9,0,3445,91.5%,13,f,0,0,7093.693707,7093.69,5600.00,1493.69,0.00,0.00,0.000,2014-05-01,2783.95,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,5,NaN,210,90.0,0,0,NaN,NaN,NaN,NaN,0,12,NaN,12,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,29364,2100,NaN
1327173,1572525,2800,2800,2800.000000,36 months,0.0762,87.26,A,A3,The Dawson Academy,7 years,MORTGAGE,65000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/20/12 > This loan is go...,major_purchase,Spa Loan,140xx,NY,5.32,0,1992-02-01,0,NaN,NaN,4,0,818,4.1%,6,f,0,0,3141.029828,3141.03,2800.00,341.03,0.00,0.00,0.000,2015-07-01,89.64,NaT,2015-06-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,1,NaN,17782,4.4,0,0,NaN,NaN,NaN,NaN,0,139,NaN,9,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,0.0,0,0,NaN,12529,18600,NaN
1363816,1607830,1925,1925,1925.000000,36 months,0.1074,62.79,B,B2,PPT,< 1 year,OWN,20700,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/20/12 > Help pay for ki...,home_improvement,Materials for home addition.,857xx,AZ,4.23,0,2002-09-01,2,NaN,NaN,7,0,2387,21.3%,10,f,0,0,1975.565136,1975.57,1925.00,50.57,0.00,0.00,0.000,2012-10-01,1850.67,NaT,2014-05-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,6,NaN,4702,22.9,0,0,NaN,NaN,NaN,NaN,0,11,NaN,0,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,50.0,0,0,NaN,12834,6100,NaN
1376522,1620885,2000,2000,2000.000000,36 months,0.1074,65.24,B,B2,Fiserv,8 years,RENT,75000,Not Verified,2012-06-01,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/21/12 > Thank you!<br>,moving,Moving Expense,064xx,CT,13.38,0,1999-03-01,0,NaN,NaN,9,0,10603,56.4%,37,f,0,0,301.780000,301.78,142.92,52.29,0.00,106.57,1.000,2012-10-01,65.24,NaT,2013-03-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,3,NaN,267,96.6,0,0,NaN,NaN,NaN,NaN,1,8,NaN,8,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,44297,7800,NaN
1375343,1619895,15000,15000,15000.000000,36 months,0.1922,551.52,D,D5,CHKD,< 1 year,RENT,135000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/20/12 > I have excellen...,credit_card,To pay off high interest credit cards,279xx,NC,11.21,0,1994-11-01,0,47,NaN,9,0,26321,87.2%,38,f,0,0,17168.480544,17168.48,15000.00,2168.48,0.00,0.00,0.000,2013-05-01,12207.55,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,0,NaN,2750,88.8,0,0,NaN,NaN,NaN,NaN,2,73,NaN,NaN,47,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,80.0,0,0,NaN,115339,24600,NaN
1375440,1619974,1400,1400,1400.000000,36 months,0.0976,45.02,B,B1,bank of america,2 years,MORTGAGE,56200,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/19/12 > Loan will be us...,vacation,Consolidate/Vacaation,891xx,NV,27.14,0,1996-11-01,0,NaN,NaN,6,0,6466,95.1%,22,f,0,0,1620.573312,1620.57,1400.00,220.57,0.00,0.00,0.000,2015-07-01,46.97,NaT,2015-06-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,2,NaN,12,99.7,0,0,NaN,NaN,NaN,NaN,1,26,NaN,14,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,19731,3500,NaN
1375177,1619715,2400,2400,2400.000000,36 months,0.1074,78.28,B,B2,"James Slaman, DDS",6 years,RENT,36500,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit Cards,871xx,NM,21.11,0,1998-11-01,0,NaN,NaN,15,0,29689,69.4%,28,f,0,0,2817.984806,2817.98,2400.00,417.98,0.00,0.00,0.000,2015-07-01,81.35,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,2,NaN,6806,80.8,0,0,NaN,NaN,NaN,NaN,0,51,NaN,7,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,15,NaN,NaN,NaN,NaN,NaN,55.6,0,0,NaN,29689,35493,NaN
1375009,1619515,2000,2000,2000.000000,36 months,0.1367,68.04,B,B5,Dekalb Farmers market,5 years,RENT,28000,Source Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/19/12 > This loan is to...,small_business,Business Start up,300xx,GA,20.40,0,2007-06-01,3,NaN,NaN,18,0,2078,40%,25,f,0,0,2326.413835,2326.41,2000.00,326.41,0.00,0.00,0.000,2014-01-01,1170.39,NaT,2014-01-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,11,NaN,26,97.4,0,0,NaN,NaN,NaN,NaN,0,61,NaN,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,18,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,70571,1000,NaN
1374780,1619092,1600,1600,1600.000000,36 months,0.0603,48.70,A,A1,Sonoma Academy,4 years,MORTGAGE,89000,Source Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/19/12 > I plan to use t...,other,Overdue Visit to Dad/Grandpa,954xx,CA,2.52,0,2002-09-01,0,NaN,NaN,6,0,9348,29.7%,16,f,0,0,1753.076105,1753.08,1600.00,153.08,0.00,0.00,0.000,2015-06-01,49.45,NaT,2015-09-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,2,NaN,4500,0.0,0,0,NaN,NaN,NaN,NaN,1,12,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,0.0,0,0,NaN,9348,4500,NaN
1374986,1619291,2000,2000,2000.000000,36 months,0.1465,68.99,C,C2,Department of Defense,5 years,MORTGAGE,50000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,Home improvement,237xx,VA,24.84,0,1995-01-01,1,NaN,NaN,10,0,30664,95.2%,18,f,0,0,2439.426083,2439.43,2000.00,439.43,0.00,0.00,0.000,2014-09-01,717.01,NaT,2015-12-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,3,NaN,553,96.8,0,0,NaN,NaN,NaN,NaN,1,40,NaN,2,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,53354,17200,NaN
1342179,1586763,4000,4000,3998.909427,36 months,0.1629,141.21,C,C5,Army Audit Agency,5 years,RENT,79000,Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/20/12 > My loan is to c...,debt_consolidation,Personal Loan,222xx,VA,15.07,0,2001-06-01,1,30,NaN,10,0,7758,87.7%,35,f,0,0,5049.120000,5047.36,4000.00,1049.12,0.00,0.00,0.000,2015-01-01,957.54,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,4,NaN,137,94.7,0,0,NaN,NaN,NaN,NaN,0,4,NaN,4,30,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,28034,2600,NaN
1374981,1619285,3600,3600,3600.000000,36 months,0.1367,122.47,B,B5,Ashford University,< 1 year,RENT,41000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/19/12 > I have a credit...,debt_consolidation,Credit Card,921xx,CA,9.86,0,2008-12-01,3,NaN,NaN,3,0,1373,59.7%,3,f,0,0,4401.789998,4401.79,3600.00,801.79,0.00,0.00,0.000,2015-04-01,483.79,NaT,2015-04-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,2,NaN,927,59.7,0,0,NaN,NaN,NaN,NaN,0,12,NaN,0,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,0.0,0,0,NaN,14150,2300,NaN
1374225,1618926,1500,1500,1500.000000,36 months,0.1212,49.91,B,B3,Insperity,9 years,RENT,51947,Source Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/19/12 > I'm a reliable ...,other,Other,770xx,TX,22.98,0,1998-01-01,3,NaN,NaN,8,0,19619,81.7%,18,f,0,0,1739.486131,1739.49,1500.00,239.49,0.00,0.00,0.000,2014-04-01,742.51,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,2,NaN,242,98.6,0,0,NaN,NaN,NaN,NaN,0,75,NaN,0,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,42883,16900,NaN
1373961,1618458,2000,2000,2000.000000,36 months,0.1399,68.35,C,C1,NaN,n/a,MORTGAGE,45000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/19/12 > We have just so...,moving,"Moving expenses, Hotel, Truck, Movers",802xx,CO,21.92,1,1995-01-01,3,2,NaN,11,0,4920,54.7%,28,f,0,0,2276.518048,2276.52,2000.00,276.52,0.00,0.00,0.000,2013-08-01,1390.53,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,6,NaN,2080,70.3,0,0,NaN,NaN,NaN,NaN,2,21,NaN,3,2,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN,NaN,NaN,50.0,0,0,NaN,85340,7000,NaN
1373675,1617910,1800,1800,1800.000000,36 months,0.1074,58.71,B,B2,Target,6 years,RENT,23000,Not Verified,2012-06-01,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/18/12 > Get rid of cred...,debt_consolidation,Credit Refinancing,986xx,WA,5.69,0,2007-01-01,0,NaN,NaN,4,0,4223,84.5%,4,f,0,0,1603.060000,1603.06,1238.01,284.85,0.00,80.20,0.802,2014-09-01,58.71,NaT,2015-01-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,1,NaN,521,88.4,0,0,NaN,NaN,NaN,NaN,0,12,NaN,12,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,66.7,0,0,NaN,4223,4500,NaN
1373438,1617684,7200,7200,7200.000000,36 months,0.1999,267.55,E,E1,Clearview Health and Rehab,< 1 year,RENT,70000,Source Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,890xx,NV,18.69,0,2001-11-01,2,NaN,NaN,27,0,7619,54.8%,30,f,0,0,9631.369995,9631.37,7200.00,2431.37,0.00,0.00,0.000,2015-07-01,279.83,NaT,2015-06-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,13,NaN,879,56.0,0,0,NaN,NaN,NaN,NaN,0,13,NaN,0,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,27,NaN,NaN,NaN,NaN,NaN,33.3,0,0,NaN,106232,2000,NaN
1372954,1617593,5000,5000,5000.000000,36 months,0.1311,168.74,B,B4,kohls,8 years,RENT,12500,Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,no credit cards,727xx,AR,13.06,0,2002-08-01,1,NaN,NaN,6,0,3190,47.6%,8,f,0,0,5811.310568,5811.31,5000.00,811.31,0.00,0.00,0.000,2014-01-01,2781.03,NaT,2014-06-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,4,NaN,502,85.7,0,0,NaN,NaN,NaN,NaN,0,14,NaN,2,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,33.3,0,0,NaN,3190,3500,NaN
1371334,1616108,2400,2400,2400.000000,36 months,0.1999,89.19,E,E1,Electralloy,1 year,RENT,37000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/18/12 > Personal Loan: ...,credit_card,Personal Loan,163xx,PA,26.34,0,2001-10-01,1,NaN,NaN,37,0,4806,11.8%,60,f,0,0,3067.397609,3067.40,2400.00,667.40,0.00,0.00,0.000,2014-04-01,1198.56,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,12,NaN,16977,20.3,0,0,NaN,NaN,NaN,NaN,0,21,NaN,0,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,37,NaN,NaN,NaN,NaN,NaN,20.0,0,0,NaN,139437,21300,NaN
1372846,1617272,1750,1750,1750.000000,36 months,0.1212,58.23,B,B3,PNC Bank,2 years,RENT,20143,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation Loan,452xx,OH,29.26,0,2008-10-01,3,NaN,NaN,18,0,1604,21.1%,22,f,0,0,2096.081194,2096.08,1750.00,346.08,0.00,0.00,0.000,2015-06-01,59.57,NaT,2015-11-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,17,NaN,1135,54.6,0,0,NaN,NaN,NaN,NaN,0,3,NaN,0,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,18,NaN,NaN,NaN,NaN,NaN,0.0,0,0,NaN,48201,2500,NaN
1372533,1617341,10000,10000,10000.000000,36 months,0.1465,344.95,C,C2,NaN,6 years,OWN,30000,Verified,2012-06-01,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Out of Debt now,322xx,FL,10.84,0,1995-10-01,0,NaN,NaN,2,0,6991,97.1%,7,f,0,0,4129.560000,4129.56,2854.69,1274.87,0.00,0.00,0.000,2013-07-01,344.95,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,0,NaN,209,97.1,0,0,NaN,NaN,NaN,NaN,1,56,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,6991,7200,NaN
1372089,1616677,4000,4000,4000.000000,36 months,0.1212,133.09,B,B3,Huntsville Memorial Hospital,5 years,MORTGAGE,50000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/18/12 > We have some cr...,credit_card,Credit Cards Be Gone,773xx,TX,5.45,0,2006-09-01,2,NaN,NaN,6,0,2257,45.1%,20,f,0,0,4791.093844,4791.09,4000.00,791.09,0.00,0.00,0.000,2015-07-01,136.63,NaT,2015-06-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,5,NaN,58,96.1,0,0,NaN,NaN,NaN,NaN,0,46,NaN,4,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,20061,1500,NaN
1370253,1614897,3000,3000,3000.000000,36 months,0.1367,102.06,B,B5,State Farm,1 year,MORTGAGE,30000,Not Verified,2012-06-01,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,other,Other,631xx,MO,13.56,0,1999-11-01,1,38,NaN,7,0,12800,73.1%,22,f,0,0,1122.110000,1122.11,790.35,331.76,0.00,0.00,0.000,2013-05-01,102.06,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,6,NaN,3200,80.0,0,0,NaN,NaN,NaN,NaN,0,6,NaN,6,38,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,75.0,0,0,NaN,12959,16000,NaN
1371821,1616400,4000,4000,4000.000000,36 months,0.0603,121.75,A,A1,POLAR ELECTRO INC,6 years,RENT,45000,Source Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/18/12 > I have only 1 c...,credit_card,ChasePayoff,115xx,NY,1.60,0,2007-01-01,0,NaN,NaN,11,0,1778,9.7%,41,f,0,0,4029.920000,4029.92,4000.00,29.92,0.00,0.00,0.000,2012-11-01,44.16,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,6,NaN,16522,9.7,0,0,NaN,NaN,NaN,NaN,0,7,NaN,14,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN,NaN,NaN,0.0,0,0,NaN,63124,18300,NaN
1370151,1615178,3000,3000,3000.000000,36 months,0.1311,101.25,B,B4,US Marine Corps,10+ years,MORTGAGE,95000,Source Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/18/12 > In preparing my...,home_improvement,Basement repair loan,224xx,VA,20.10,2,1993-10-01,0,12,NaN,9,0,18141,94.5%,33,f,0,0,3642.010000,3642.01,3000.00,642.01,0.00,0.00,0.000,2015-04-01,389.16,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,1,NaN,226,97.8,0,0,NaN,NaN,NaN,NaN,0,49,NaN,7,12,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,65860,10500,NaN
1365045,1609144,1200,1200,1200.000000,36 months,0.1212,39.93,B,B3,Target,4 years,MORTGAGE,45000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/18/12 > Ever have one o...,debt_consolidation,debt consolidation Loan,442xx,OH,17.19,0,2000-03-01,0,NaN,NaN,22,0,9806,84.5%,29,f,0,0,1437.306684,1437.31,1200.00,237.31,0.00,0.00,0.000,2015-06-01,40.98,NaT,2015-06-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,8,NaN,107,98.2,0,0,NaN,NaN,NaN,NaN,1,12,NaN,12,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,60576,6000,NaN
1371169,1615924,3900,3900,3900.000000,36 months,0.1367,132.67,B,B5,FGH,3 years,MORTGAGE,60000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/18/12 > I'm trying to e...,credit_card,Credit Card Consolidation,265xx,WV,20.42,0,2005-10-01,0,NaN,NaN,14,0,12493,60.6%,28,f,0,0,4752.564804,4752.56,3900.00,852.56,0.00,0.00,0.000,2015-07-01,60.22,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,4,NaN,3610,71.6,0,0,NaN,NaN,NaN,NaN,1,18,NaN,22,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,14,NaN,NaN,NaN,NaN,NaN,66.7,0,0,NaN,47464,12700,NaN
1370829,1615512,1500,1500,1500.000000,36 months,0.1212,49.91,B,B3,Buda Woodworks LP,10+ years,MORTGAGE,76450,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,Home Improvement Loan,786xx,TX,17.39,0,1995-10-01,0,48,NaN,13,0,10305,56.6%,33,f,0,0,1796.651247,1796.65,1500.00,296.65,0.00,0.00,0.000,2015-07-01,51.49,NaT,2016-02-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,6,NaN,0,102.8,0,0,NaN,NaN,NaN,NaN,1,10,NaN,10,48,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,13,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,43942,7200,NaN
1370575,1615204,2500,2500,2500.000000,36 months,0.1311,84.37,B,B4,Lowes,5 years,RENT,85000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Payoff,310xx,GA,3.08,0,2009-03-01,2,NaN,NaN,10,0,0,0%,13,f,0,0,2678.304548,2678.30,2500.00,178.30,0.00,0.00,0.000,2013-01-01,2173.38,NaT,2015-05-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,12,NaN,2400,0.0,0,0,NaN,NaN,NaN,NaN,0,1,NaN,0,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,0.0,0,0,NaN,29439,2400,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1365476,1609599,1000,1000,1000.000000,36 months,0.1825,36.28,D,D3,Oakley,3 years,RENT,41000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,wedding,Wedding Fund,656xx,MO,22.01,0,2004-09-01,0,42,NaN,5,0,4005,93.1%,6,f,0,0,1305.981821,1305.98,1000.00,305.98,0.00,0.00,0.000,2015-06-01,38.07,NaT,2015-06-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,4,NaN,257,93.6,0,0,NaN,NaN,NaN,NaN,0,94,NaN,17,42,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,100.0,0,0,NaN,29355,4000,NaN
1365453,1609573,5000,5000,5000.000000,36 months,0.0890,158.77,A,A5,Bombardier Aerospace,3 years,RENT,35000,Not Verified,2012-06-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 06/14/12 > I want to be co...,debt_consolidation,Debt free fund,263xx,WV,1.82,0,2001-10-01,0,NaN,NaN,2,0,2729,44.7%,17,f,0,0,5715.560000,5715.56,5000.00,715.56,0.00,0.00,0.000,2015-07-01,167.66,NaT,2015-06-01,0,NaN,1,INDIVIDUAL,0,NaN,NaN,NaN,0,NaN,3373,44.7,0,0,NaN,NaN,NaN,NaN,0,79,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,0.0,0,0,NaN,2729,6102,NaN

In [36]:
past_loans[(past_loans['loan_status'] != "Charged Off") & (past_loans['loan_status'] != "Fully Paid")].head(100)

Empty DataFrame
Columns: [member_id, loan_amnt, funded_amnt, funded_amnt_inv, term, int_rate, installment, grade, sub_grade, emp_title, emp_length, home_ownership, annual_inc, verification_status, issue_d, loan_status, pymnt_plan, url, desc, purpose, title, zip_code, addr_state, dti, delinq_2yrs, earliest_cr_line, inq_last_6mths, mths_since_last_delinq, mths_since_last_record, open_acc, pub_rec, revol_bal, revol_util, total_acc, initial_list_status, out_prncp, out_prncp_inv, total_pymnt, total_pymnt_inv, total_rec_prncp, total_rec_int, total_rec_late_fee, recoveries, collection_recovery_fee, last_pymnt_d, last_pymnt_amnt, next_pymnt_d, last_credit_pull_d, collections_12_mths_ex_med, mths_since_last_major_derog, policy_code, application_type, acc_now_delinq, tot_coll_amt, tot_cur_bal, total_rev_hi_lim, acc_open_past_24mths, avg_cur_bal, bc_open_to_buy, bc_util, chargeoff_within_12_mths, delinq_amnt, mo_sin_old_il_acct, mo_sin_old_rev_tl_op, mo_sin_rcnt_rev_tl_op, mo_sin_rcnt_tl, mort_acc, mths_since_recent_bc, mths_since_recent_bc_dlq, mths_since_recent_inq, mths_since_recent_revol_delinq, num_accts_ever_120_pd, num_actv_bc_tl, num_actv_rev_tl, num_bc_sats, num_bc_tl, num_il_tl, num_op_rev_tl, num_rev_accts, num_rev_tl_bal_gt_0, num_sats, num_tl_120dpd_2m, num_tl_30dpd, num_tl_90g_dpd_24m, num_tl_op_past_12m, pct_tl_nvr_dlq, percent_bc_gt_75, pub_rec_bankruptcies, tax_liens, tot_hi_cred_lim, total_bal_ex_mort, total_bc_limit, total_il_high_credit_limit]
Index: []

# Explore different categorical data
What values are inside the categorical fields?

In [37]:
pd.unique(past_loans['term'])

array([' 36 months'], dtype=object)

In [38]:
pd.unique(past_loans['grade'])

array(['C', 'A', 'D', 'B', 'E', 'G', 'F'], dtype=object)

In [39]:
pd.unique(past_loans['sub_grade'])

array(['C2', 'A4', 'D5', 'A3', 'B2', 'B1', 'B5', 'A1', 'C5', 'B3', 'C1',
       'E1', 'B4', 'D1', 'C4', 'D3', 'A2', 'E2', 'E4', 'A5', 'D2', 'C3',
       'D4', 'G1', 'G2', 'E5', 'F1', 'G3', 'F5', 'F2', 'E3', 'F3', 'G4',
       'G5', 'F4'], dtype=object)

In [40]:
pd.unique(past_loans['home_ownership'])

array(['MORTGAGE', 'RENT', 'OWN'], dtype=object)

In [41]:
pd.unique(past_loans['verification_status'])

array(['Source Verified', 'Not Verified', 'Verified'], dtype=object)

In [42]:
pd.unique(past_loans['loan_status'])

array(['Fully Paid', 'Charged Off'], dtype=object)

In [43]:
pd.unique(past_loans['pymnt_plan'])

array(['n'], dtype=object)

In [44]:
pd.unique(past_loans['purpose'])

array(['home_improvement', 'car', 'debt_consolidation', 'major_purchase',
       'moving', 'credit_card', 'vacation', 'small_business', 'other',
       'wedding', 'medical', 'house', 'renewable_energy'], dtype=object)

# Examine field types and amount of data
Is there any missing data?

In [45]:
past_loans.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14967 entries, 1377559 to 1058722
Data columns (total 93 columns):
member_id                         14967 non-null int64
loan_amnt                         14967 non-null int64
funded_amnt                       14967 non-null int64
funded_amnt_inv                   14967 non-null float64
term                              14967 non-null category
int_rate                          14967 non-null float64
installment                       14967 non-null float64
grade                             14967 non-null category
sub_grade                         14967 non-null category
emp_title                         13938 non-null object
emp_length                        14967 non-null object
home_ownership                    14967 non-null category
annual_inc                        14967 non-null float64
verification_status               14967 non-null category
issue_d                           14967 non-null datetime64[ns]
loan_status                       14967 non-null category
pymnt_plan                        14967 non-null category
url                               14967 non-null object
desc                              8511 non-null object
purpose                           14967 non-null category
title                             14967 non-null object
zip_code                          14967 non-null object
addr_state                        14967 non-null object
dti                               14967 non-null float64
delinq_2yrs                       14967 non-null int64
earliest_cr_line                  14967 non-null datetime64[ns]
inq_last_6mths                    14967 non-null int64
mths_since_last_delinq            4777 non-null float64
mths_since_last_record            434 non-null float64
open_acc                          14967 non-null int64
pub_rec                           14967 non-null int64
revol_bal                         14967 non-null int64
revol_util                        14947 non-null object
total_acc                         14967 non-null int64
initial_list_status               14967 non-null object
out_prncp                         14967 non-null float64
out_prncp_inv                     14967 non-null float64
total_pymnt                       14967 non-null float64
total_pymnt_inv                   14967 non-null float64
total_rec_prncp                   14967 non-null float64
total_rec_int                     14967 non-null float64
total_rec_late_fee                14967 non-null float64
recoveries                        14967 non-null float64
collection_recovery_fee           14967 non-null float64
last_pymnt_d                      14949 non-null datetime64[ns]
last_pymnt_amnt                   14967 non-null float64
next_pymnt_d                      0 non-null datetime64[ns]
last_credit_pull_d                14967 non-null datetime64[ns]
collections_12_mths_ex_med        14967 non-null int64
mths_since_last_major_derog       0 non-null float64
policy_code                       14967 non-null int64
application_type                  14967 non-null category
acc_now_delinq                    14967 non-null int64
tot_coll_amt                      0 non-null float64
tot_cur_bal                       0 non-null float64
total_rev_hi_lim                  0 non-null float64
acc_open_past_24mths              8942 non-null float64
avg_cur_bal                       0 non-null float64
bc_open_to_buy                    8827 non-null float64
bc_util                           8821 non-null float64
chargeoff_within_12_mths          14967 non-null int64
delinq_amnt                       14967 non-null int64
mo_sin_old_il_acct                0 non-null float64
mo_sin_old_rev_tl_op              0 non-null float64
mo_sin_rcnt_rev_tl_op             0 non-null float64
mo_sin_rcnt_tl                    0 non-null float64
mort_acc                          8942 non-null float64
mths_since_recent_bc              8840 non-null float64
mths_since_recent_bc_dlq          0 non-null float64
mths_since_recent_inq             7580 non-null float64
mths_since_recent_revol_delinq    2138 non-null float64
num_accts_ever_120_pd             0 non-null float64
num_actv_bc_tl                    0 non-null float64
num_actv_rev_tl                   0 non-null float64
num_bc_sats                       2008 non-null float64
num_bc_tl                         0 non-null float64
num_il_tl                         0 non-null float64
num_op_rev_tl                     0 non-null float64
num_rev_accts                     0 non-null float64
num_rev_tl_bal_gt_0               0 non-null float64
num_sats                          2008 non-null float64
num_tl_120dpd_2m                  0 non-null float64
num_tl_30dpd                      0 non-null float64
num_tl_90g_dpd_24m                0 non-null float64
num_tl_op_past_12m                0 non-null float64
pct_tl_nvr_dlq                    0 non-null float64
percent_bc_gt_75                  8827 non-null float64
pub_rec_bankruptcies              14967 non-null int64
tax_liens                         14967 non-null int64
tot_hi_cred_lim                   0 non-null float64
total_bal_ex_mort                 8942 non-null float64
total_bc_limit                    8942 non-null float64
total_il_high_credit_limit        0 non-null float64
dtypes: category(9), datetime64[ns](5), float64(54), int64(16), object(9)
memory usage: 9.8+ MB

# Check out summary stats on the numeric fields

In [46]:
past_loans.describe().transpose() #.to_string()

,count,mean,std,min,25%,50%,75%,max
member_id,14967,1455102.984499,95085.641457,382664.00,1383155.500000,1456996.0000,1531193.000000,1622372.000000
loan_amnt,14967,11601.224360,7188.093122,1000.00,6325.000000,10000.0000,15000.000000,35000.000000
funded_amnt,14967,11601.224360,7188.093122,1000.00,6325.000000,10000.0000,15000.000000,35000.000000
funded_amnt_inv,14967,11577.779687,7173.743526,950.00,6300.000000,10000.0000,15000.000000,35000.000000
int_rate,14967,0.118843,0.037323,0.06,0.089000,0.1212,0.142700,0.248900
installment,14967,387.315191,246.678443,30.44,208.750000,337.3800,496.800000,1379.230000
annual_inc,14967,66678.824698,43712.992175,5000.00,40000.000000,57000.0000,80000.000000,1233000.000000
dti,14967,14.849731,6.776538,0.00,9.750000,14.9000,20.020000,34.920000
delinq_2yrs,14967,0.131422,0.505779,0.00,0.000000,0.0000,0.000000,10.000000
inq_last_6mths,14967,0.766553,0.983709,0.00,0.000000,0.0000,1.000000,8.000000
mths_since_last_delinq,4777,38.594515,21.238001,1.00,21.000000,37.0000,54.000000,108.000000
mths_since_last_record,434,93.322581,22.385497,1.00,89.000000,99.0000,108.000000,119.000000
open_acc,14967,9.908933,4.279092,2.00,7.000000,9.0000,12.000000,49.000000
pub_rec,14967,0.029665,0.174712,0.00,0.000000,0.0000,0.000000,4.000000
revol_bal,14967,13509.266854,12519.771355,0.00,5949.500000,10687.0000,17484.000000,149509.000000
total_acc,14967,21.852743,10.621712,3.00,14.000000,20.0000,28.000000,68.000000
out_prncp,14967,0.000000,0.000000,0.00,0.000000,0.0000,0.000000,0.000000
out_prncp_inv,14967,0.000000,0.000000,0.00,0.000000,0.0000,0.000000,0.000000
total_pymnt,14967,12629.793503,8628.024146,0.00,6524.541549,11029.1800,16435.163946,49567.279975
total_pymnt_inv,14967,12610.997262,8616.879588,0.00,6509.480000,11006.6800,16422.540000,49567.280000
total_rec_prncp,14967,10658.862063,7287.732960,0.00,5400.000000,9600.0000,14000.000000,35000.000000
total_rec_int,14967,1895.195312,1696.418596,0.00,770.820000,1428.5000,2440.980000,14552.280000
total_rec_late_fee,14967,0.792168,5.456035,0.00,0.000000,0.0000,0.000000,134.010000
recoveries,14967,74.943951,409.042144,0.00,0.000000,0.0000,0.000000,15581.060000
collection_recovery_fee,14967,4.721607,54.859303,0.00,0.000000,0.0000,0.000000,3703.430000
last_pymnt_amnt,14967,2693.840138,4196.354440,0.00,304.865000,663.8600,3516.195000,35285.310000
collections_12_mths_ex_med,14967,0.000000,0.000000,0.00,0.000000,0.0000,0.000000,0.000000
mths_since_last_major_derog,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
policy_code,14967,1.000000,0.000000,1.00,1.000000,1.0000,1.000000,1.000000
acc_now_delinq,14967,0.000000,0.000000,0.00,0.000000,0.0000,0.000000,0.000000
...,...,...,...,...,...,...,...,...
mo_sin_old_rev_tl_op,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mo_sin_rcnt_rev_tl_op,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mo_sin_rcnt_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mort_acc,8942,1.304742,2.035491,0.00,0.000000,0.0000,2.000000,22.000000
mths_since_recent_bc,8840,23.718100,27.306367,0.00,6.000000,13.0000,34.000000,413.000000
mths_since_recent_bc_dlq,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mths_since_recent_inq,7580,7.079947,6.255791,0.00,2.000000,5.0000,11.000000,24.000000
mths_since_recent_revol_delinq,2138,40.313377,20.749842,1.00,24.000000,40.0000,56.000000,98.000000
num_accts_ever_120_pd,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_actv_bc_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_actv_rev_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_bc_sats,2008,4.646414,2.470650,0.00,3.000000,4.0000,6.000000,20.000000
num_bc_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_il_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_op_rev_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_rev_accts,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_rev_tl_bal_gt_0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_sats,2008,10.938745,4.703647,2.00,8.000000,10.0000,14.000000,37.000000
num_tl_120dpd_2m,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_tl_30dpd,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_tl_90g_dpd_24m,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_tl_op_past_12m,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pct_tl_nvr_dlq,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
percent_bc_gt_75,8827,50.316382,35.458767,0.00,20.000000,50.0000,80.000000,100.000000
pub_rec_bankruptcies,14967,0.023786,0.153260,0.00,0.000000,0.0000,0.000000,2.000000
tax_liens,14967,0.000000,0.000000,0.00,0.000000,0.0000,0.000000,0.000000
tot_hi_cred_lim,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_bal_ex_mort,8942,34795.245023,33476.214916,0.00,14388.500000,26173.5000,43766.500000,819312.000000
total_bc_limit,8942,18805.242228,18696.834220,0.00,7200.000000,13400.0000,24100.000000,301720.000000
total_il_high_credit_limit,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Explore date fields

In [47]:
past_loans.groupby(past_loans['last_pymnt_d'].map(lambda x: x.year))

In [48]:
pd.unique(past_loans.sort_values('last_pymnt_d')['last_pymnt_d'])

array(['2012-01-31T19:00:00.000000000-0500',
       '2012-02-29T19:00:00.000000000-0500',
       '2012-03-31T20:00:00.000000000-0400',
       '2012-04-30T20:00:00.000000000-0400',
       '2012-05-31T20:00:00.000000000-0400',
       '2012-06-30T20:00:00.000000000-0400',
       '2012-07-31T20:00:00.000000000-0400',
       '2012-08-31T20:00:00.000000000-0400',
       '2012-09-30T20:00:00.000000000-0400',
       '2012-10-31T20:00:00.000000000-0400',
       '2012-11-30T19:00:00.000000000-0500',
       '2012-12-31T19:00:00.000000000-0500',
       '2013-01-31T19:00:00.000000000-0500',
       '2013-02-28T19:00:00.000000000-0500',
       '2013-03-31T20:00:00.000000000-0400',
       '2013-04-30T20:00:00.000000000-0400',
       '2013-05-31T20:00:00.000000000-0400',
       '2013-06-30T20:00:00.000000000-0400',
       '2013-07-31T20:00:00.000000000-0400',
       '2013-08-31T20:00:00.000000000-0400',
       '2013-09-30T20:00:00.000000000-0400',
       '2013-10-31T20:00:00.000000000-0400',
       '2013-11-30T19:00:00.000000000-0500',
       '2013-12-31T19:00:00.000000000-0500',
       '2014-01-31T19:00:00.000000000-0500',
       '2014-02-28T19:00:00.000000000-0500',
       '2014-03-31T20:00:00.000000000-0400',
       '2014-04-30T20:00:00.000000000-0400',
       '2014-05-31T20:00:00.000000000-0400',
       '2014-06-30T20:00:00.000000000-0400',
       '2014-07-31T20:00:00.000000000-0400',
       '2014-08-31T20:00:00.000000000-0400',
       '2014-09-30T20:00:00.000000000-0400',
       '2014-10-31T20:00:00.000000000-0400',
       '2014-11-30T19:00:00.000000000-0500',
       '2014-12-31T19:00:00.000000000-0500',
       '2015-01-31T19:00:00.000000000-0500',
       '2015-02-28T19:00:00.000000000-0500',
       '2015-03-31T20:00:00.000000000-0400',
       '2015-04-30T20:00:00.000000000-0400',
       '2015-05-31T20:00:00.000000000-0400',
       '2015-06-30T20:00:00.000000000-0400',
       '2015-07-31T20:00:00.000000000-0400',
       '2015-08-31T20:00:00.000000000-0400',
       '2015-09-30T20:00:00.000000000-0400',
       '2015-10-31T20:00:00.000000000-0400', 'NaT'], dtype='datetime64[ns]')

In [49]:
pd.unique(past_loans['issue_d'])

array(['2012-05-31T20:00:00.000000000-0400',
       '2012-04-30T20:00:00.000000000-0400',
       '2012-03-31T20:00:00.000000000-0400',
       '2012-02-29T19:00:00.000000000-0500',
       '2012-01-31T19:00:00.000000000-0500',
       '2011-12-31T19:00:00.000000000-0500'], dtype='datetime64[ns]')

Scatter plot of default frequency vs (last payment - issue date), maybe group by

# Fill in rows for each date to last payment
A simple look at the data will be skewed because active loans may still default in the future. Only using 2012 36 month loans.

The data is supplied with status for each loan. Best to fill data with records for each month from loan start (and status = current) until today or last payment). This will allow me to determine the shape of the conditional default curve (what percentage of current loans default vs age?) and then use the current data set. I will also gain a better understanding of Loss Given Default for this data set.

Not sure if I have time to make this happen. When I do, I will go back and import data from 2013+.

## Create list of possible dates to match with

In [16]:
# What are all the dates in the table?
# for each date, what are the earlier dates
# create new table with "current" until paid or written off
# table should stop before defaults and late payments start registering

In [20]:
all_dates = pd.DataFrame(index=pd.unique(past_loans.sort_values('last_pymnt_d')['last_pymnt_d']))#, columns='date_d')
all_dates['report_d'] = pd.unique(past_loans.sort_values('last_pymnt_d')['last_pymnt_d'])
all_dates['common'] = 1
all_dates.dropna(how = 'any')
all_dates[(pd.notnull(all_dates['report_d']))]

             report_d  common
2014-02-01 2014-02-01       1
2014-03-01 2014-03-01       1
2014-04-01 2014-04-01       1
2014-05-01 2014-05-01       1
2014-06-01 2014-06-01       1
2014-07-01 2014-07-01       1
2014-08-01 2014-08-01       1
2014-09-01 2014-09-01       1
2014-10-01 2014-10-01       1
2014-11-01 2014-11-01       1
2014-12-01 2014-12-01       1
2015-01-01 2015-01-01       1
2015-02-01 2015-02-01       1
2015-03-01 2015-03-01       1
2015-04-01 2015-04-01       1
2015-05-01 2015-05-01       1
2015-06-01 2015-06-01       1
2015-07-01 2015-07-01       1
2015-08-01 2015-08-01       1
2015-09-01 2015-09-01       1
2015-10-01 2015-10-01       1
2015-11-01 2015-11-01       1
2015-12-01 2015-12-01       1

In [50]:
# ro's idea - just loop through the data to create the data

# past_loans['common'] = 1
# partly_merged = pd.merge(past_loans, all_dates, on = 'common')
# full_past_loans = partly_merged[(partly_merged['last_pymnt_d'] >= partly_merged['report_d'] & 
#                                 pd.notnull(partly_merged['report_d']))]
# full_past_loans.head(100)

# Create dependent and independent data

In [51]:
X = past_loans.drop('loan_status', axis = 1)
y = past_loans['loan_status']

# Split into training and test data

In [52]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
# 10 cross validation iterations with 20% test / 80% train
from sklearn.cross_validation import ShuffleSplit
cv = ShuffleSplit(X_train.shape[0], n_iter=10, test_size=0.2, random_state=0)

# Standardize the data

In [53]:
from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
# transform our training features
X_train_std = stdsc.fit_transform(X_train)
# transform the testing features in the same way
X_test_std = stdsc.transform(X_test)

ValueError: could not convert string to float: INDIVIDUAL